FROM scratch
MAINTAINER Fabian Clerbois <fabian@bowlman.org>
ADD http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/12.0-RELEASE/base.txz /
WORKDIR /tmp/vlang
RUN pkg install upgrade && pkg install gcc git gmake
CMD ["/bin/sh"]
